services:
  - type: web
    name: iot-dashboard-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /health
    autoDeploy: true
    # Reduce the number of health checks to avoid rate limiting
    healthCheckTimeout: 300
    healthCheckInterval: 300 